#!/bin/sh

# This source is part of UnitKit, a unit test framework for Mac OS X 
# development. You can find more information about UnitKit at:
# 
# http://x180.net/Code/UnitKit
# 
# Copyright (c)2004 James Duncan Davidson
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# The use of the Apache License does not indicate that this project is
# affiliated with the Apache Software Foundation.

# DOCUMENTATION
#
# This is a quicky little cheesy uninstallation script which will yank UnitKit
# right out of a home directory installation

echo
echo "NOTE:"
echo "You may be asked for an administrator password. This is because"
echo "the various pieces have been installed into /usr/local/bin and /Library"
echo "The password is being requested by sudo and not this script."
echo


#
# (nat) this script is totally rewritten
#
remove_path()
{
   local path
   
   path="$1"
   shift
   
   if [ -e "$path" ]
   then
      echo "Removing $path"
      rm -rf "$path"
   fi
}


remove_from_directory_with_prefixes()
{
   local file
   local dir
   local prefix
   
   file="$1"
   shift
   
   dir="$1"
   shift

   prefix="$1"
   shift
   
   while [ "$prefix" != "" ]
   do
       remove_path "$prefix/$dir/$file"
       dir="$1"
       shift
   done
}
   
   
remove_from_directory_with_prefixes ukrun bin                             ~ /usr/local

remove_from_directory_with_prefixes libunit_objc_kit.so lib               ~ /usr/local 
remove_from_directory_with_prefixes libunit_objc_kit.a  lib               ~ /usr/local 

remove_from_directory_with_prefixes libunit_c_kit.so    lib               ~ /usr/local 
remove_from_directory_with_prefixes libunit_c_kit.a     lib               ~ /usr/local 

remove_from_directory_with_prefixes UnitKit.framework Library/Frameworks  ~ /

#
# these are moving targets, because Xcode guys are extremely moody
#
remove_from_directory_with_prefixes "UnitKit Bundle.trgttmpl"          "Library/Application Support/Developer/Shared/Xcode/Target Templates" ~ /
remove_from_directory_with_prefixes "UnitKitDebug Bundle.trgttmpl"     "Library/Application Support/Developer/Shared/Xcode/Target Templates" ~ /
remove_from_directory_with_prefixes "UnitKit TestClass.pbfiletemplate" "Library/Application Support/Developer/Shared/Xcode/File Templates" ~ /


if [ -f "/Library/Receipts/UnitKit.pkg" ]
then
  echo "Removing Package Receipt"
  sudo rm -rf "/Library/Receipts/UnitKit.pkg"
fi

